### ISSUE TITLE
Task.Run?

### ISSUE THREAD

**Issue by SaebAmini** [tyrotoxin/Microsoft.Xrm.Sdk.Async#1]
I was glad to find this package, however, looking at the source code, I noticed `Task.Run` is being used to wrap everything in async methods. e.g. : https://github.com/tyrotoxin/Microsoft.Xrm.Sdk.Async/blob/master/OrganizationService/AsyncOrganizationServiceProxy.AsyncMethods.cs

`Task.Run` uses Threadpool threads, which defeats the purpose of using asynchrony for I/O bound operations and the purpose of this library which would be avoiding unnecessary threads.

The hit is negligible here because as soon as the first `await` is hit, the threadpool thread is released and there isn't anything else after the `await` which will need the threadpool thread, however, it's still being borrowed for zero gain. You can simply return the result of ` Task.Factory.FromAsync` from the implementations to make them truly asynchronous.

**Comment by kind-serge** [comment]
Hi, true. I have no idea why I did it like that :) Do you want to contribute by any chance?

**Comment by SaebAmini** [comment]
@tyrotoxin sorry was a bit caught up. Just submitted a PR :)

**Comment by kind-serge** [comment]
@SaebAmini, the PR #2 has been merged in, and is available at nuget.org with version *.0.4

**Comment by SaebAmini** [comment]
Perfect!
